version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    # networks:
    #   - nest-network

#   nest-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: nest-app
#     ports:
#       - 3333:3333
#     environment:
#       PORT: 3333
#       FRONTEND_URL: http://localhost:8080
#       DATABASE_URL: postgresql://postgres:docker@localhost:5432/nest-clean?schema=public
#       AMI_PORT: 5038
#       AMI_HOST: 172.17.0.1
#       AMI_USERNAME: nestAPI
#       AMI_PASSWORD: NestAPItecno1710

#     depends_on:
#       - postgres
#     networks:
#       - nest-network

# networks:
#   nest-network:
#     driver: bridge
